FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Copy the app code
COPY . .

# Copy .env into the image
#COPY .env .env

EXPOSE 8000

CMD ["sh", "-c", "alembic upgrade head && python seed.py && uvicorn main:app --host 0.0.0.0 --port 8000"]
#CMD alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
