"""add icon column to data

Revision ID: 3feaec0aa2e1
Revises: 78fda5ef2e25
Create Date: 2025-08-29 16:57:53.020261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3feaec0aa2e1'
down_revision: Union[str, Sequence[str], None] = '78fda5ef2e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('promotions_icon_key'), 'promotions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('promotions_icon_key'), 'promotions', ['icon'])
    # ### end Alembic commands ###
