"""add icon columns

Revision ID: 78fda5ef2e25
Revises: fd7dcf3daa95
Create Date: 2025-08-25 21:16:22.835910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fda5ef2e25'
down_revision: Union[str, Sequence[str], None] = 'fd7dcf3daa95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('icon', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'promotions', ['icon'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promotions', type_='unique')
    op.drop_column('promotions', 'icon')
    # ### end Alembic commands ###
